export const colors = {
  holo: {
    cyan: 'rgba(0, 255, 255, %alpha)',
    'cyan-dim': 'rgba(0, 204, 204, %alpha)',
    'cyan-dark': '#001a1a',
    blue: 'rgba(0, 136, 255, %alpha)',
    green: 'rgba(0, 255, 170, %alpha)',
    purple: 'rgba(170, 136, 255, %alpha)',
  },
  scene: {
    void: 'rgba(0, 10, 14, %alpha)',
    deep: 'rgba(0, 16, 24, %alpha)',
    surface: 'rgba(0, 26, 40, %alpha)',
  },
  status: {
    success: 'rgba(0, 255, 136, %alpha)',
    warning: 'rgba(255, 170, 0, %alpha)',
    error: 'rgba(255, 85, 102, %alpha)',
  },
  surface: {
    canvas: 'var(--shd-surface-canvas)',
    base: { DEFAULT: 'var(--shd-surface-base)', soft: 'var(--shd-surface-base-soft)' },
    raised: { DEFAULT: 'var(--shd-surface-raised)', soft: 'var(--shd-surface-raised-soft)' },
    overlay: { DEFAULT: 'var(--shd-surface-overlay)', soft: 'var(--shd-surface-overlay-soft)' },
    interactive: { DEFAULT: 'var(--shd-surface-interactive)', hover: 'var(--shd-surface-interactive-hover)' },
    selected: 'var(--shd-surface-selected)',
  },
  content: {
    primary: 'var(--shd-content-primary)',
    secondary: 'var(--shd-content-secondary)',
    tertiary: 'var(--shd-content-tertiary)',
    disabled: 'var(--shd-content-disabled)',
    accent: 'var(--shd-content-accent)',
  },
  stroke: {
    muted: 'var(--shd-stroke-muted)',
    subtle: 'var(--shd-stroke-subtle)',
    default: 'var(--shd-stroke-default)',
    strong: 'var(--shd-stroke-strong)',
    accent: { DEFAULT: 'var(--shd-stroke-accent)', strong: 'var(--shd-stroke-accent-strong)' },
    success: 'var(--shd-stroke-success)',
    warning: 'var(--shd-stroke-warning)',
    error: 'var(--shd-stroke-error)',
  },
  accent: {
    primary: {
      DEFAULT: 'var(--shd-accent-primary)',
      hover: 'var(--shd-accent-primary-hover)',
      active: 'var(--shd-accent-primary-active)',
      soft: 'var(--shd-accent-primary-soft)',
      softer: 'var(--shd-accent-primary-softer)',
    },
    blue: { DEFAULT: 'var(--shd-accent-blue)', soft: 'var(--shd-accent-blue-soft)' },
    purple: { DEFAULT: 'var(--shd-accent-purple)', soft: 'var(--shd-accent-purple-soft)' },
  },
  state: {
    success: { soft: 'var(--shd-success-soft)' },
    warning: { soft: 'var(--shd-warning-soft)' },
    error: { soft: 'var(--shd-error-soft)' },
  },
  focus: 'var(--shd-focus-ring)',
}
